[package]
name = "test-support"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
comenqd = { path = "../crates/comenqd" }
octocrab = { workspace = true }
tempfile = { workspace = true }
wiremock = "^0.6"
