[package]
name = "test-support"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
octocrab = { workspace = true }
tempfile = { workspace = true }
wiremock = "^0.6"
serde_yaml = { workspace = true }

[dev-dependencies]
serial_test = "^2"
