name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
      BUILD_PROFILE: debug
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust
        uses: leynos/shared-actions/.github/actions/setup-rust@0ac4b6ec81dbef45594b37bc2afaaa60e30b5b20
      - name: Format
        run: make check-fmt
      - name: Lint
        run: make lint
      - name: Test Only
        run: make test
      - name: Test and Measure Coverage
        uses: leynos/shared-actions/.github/actions/generate-coverage@0ac4b6ec81dbef45594b37bc2afaaa60e30b5b20
        with:
          output-path: lcov.info
          format: lcov
      - name: Upload coverage data to CodeScene
        env:
          CS_ACCESS_TOKEN: ${{ secrets.CS_ACCESS_TOKEN }}
        if: ${{ env.CS_ACCESS_TOKEN }}
        uses: leynos/shared-actions/.github/actions/upload-codescene-coverage@0ac4b6ec81dbef45594b37bc2afaaa60e30b5b20
        with:
          format: lcov
          access-token: ${{ env.CS_ACCESS_TOKEN }}
          installer-checksum: ${{ vars.CODESCENE_CLI_SHA256 }}
